### PR TITLE
Fix go package dependencies.

### LINKED ISSUE #10: Dependency repostiory termtables no longer exists
Looks like the repository no longer exists.
https://github.com/apcera/termtables gives me a 404 error.

### PR DESCRIPTION
**Pull request by ashyablok**
closes #10 
Also updates the use of the github.com/urfave/cli to latest version.

### CODE REVIEW

File: cmds/main.go [hunk 1]
```diff
@@ -134,14 +135,31 @@ func resultWriteCSV(list []lytics.TableWriter, name string) {
...
+		table.Append(rowToString(row.Row()))
 	}
-	fmt.Println(table.Render())
+	table.SetAutoFormatHeaders(false)
+	table.Render()
+	fmt.Println(tableString.String())
+}
+
+func rowToString(row []interface{}) []string {
+	res := []string{}
```
Comment (mattayes) [inline cmds/main.go]: [NIT] Since we're adding everything from `row` to the output you might as well make this slice that big to begin with:

```suggestion
	res := make([]string, 0, len(row))
```

File: cmds/main.go [hunk 2]
```diff
@@ -134,14 +135,31 @@ func resultWriteCSV(list []lytics.TableWriter, name string) {
...
+	for _, val := range row {
+		str, ok := val.(string)
+		if ok {
+			res = append(res, str)
+			continue
+		}
+		res = append(res, fmt.Sprintf("%v", val))
```
Comment (mattayes) [inline cmds/main.go]: [NIT] If you're using the default print verb (`%v`) you can use [`Sprint()`](https://godoc.org/fmt#Sprint) here.

```suggestion
		res = append(res, fmt.Sprint(val))
```

**Review by mattayes — APPROVED** [review]
LGTM. We should be pinning our dependencies using Go modules.

**Review by lizbeacham — APPROVED** [review]
+1 for using Go modules as @mattayes mentioned, but otherwise looks ok to me :rocket:
